### ISSUE TITLE
The library is available on Mac ?

### ISSUE THREAD

**Issue by Apicpic** [enwi/hueplusplus#21]
I'm looking for a library to program my Hue in C++ and on Mac.

**Comment by Apicpic** [comment]
Cool, I begin to test it and I have a problem with handler = std::make_shared<LinHttpHandler>();
Do you have a special command for MacOS ?

**Comment by enwi** [comment]
Can you give me a minimal working example (even if not working :smile: )?

**Comment by Apicpic** [comment]
I'm just trying to do the readme example to find bridges : 
#include <iostream>
#include "hueplusplus/Hue.h"

using namespace std;

int main()
{
        auto handler = std::make_shared<LinHttpHandler>();
        HueFinder finder(handler);
        std::vector<HueFinder::HueIdentification> bridges;
        if (bridges.empty())
        {
                bridges.push_back({"168.254.7.112", "001788FFFE67A24F" });
        }
        Hue bridge = finder.GetBridge(bridges[0]);
        return 0;
}

**Comment by enwi** [comment]
You are missing the include for LinHttpHandler so add `#include "hueplusplus/LinHttpHandler.h"`

**Comment by Apicpic** [comment]
Sorry, I had included LinHttpHandler and when I did that I have this : 

Undefined symbols for architecture x86_64:
  "Json::CharReaderBuilder::CharReaderBuilder()", referenced from:
      BaseHttpHandler::strToJsonValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const in test-479ca2.o
  "Json::CharReaderBuilder::~CharReaderBuilder()", referenced from:
      BaseHttpHandler::strToJsonValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const in test-479ca2.o
  "Json::CharReaderBuilder::operator[](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      BaseHttpHandler::strToJsonValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const in test-479ca2.o
  "Json::Value::Value(Json::ValueType)", referenced from:
      BaseHttpHandler::strToJsonValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const in test-479ca2.o
  "Json::Value::Value(bool)", referenced from:
      BaseHttpHandler::strToJsonValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const in test-479ca2.o
  "Json::Value::~Value()", referenced from:
      Hue::~Hue() in test-479ca2.o
      HueLight::~HueLight() in test-479ca2.o
      BaseHttpHandler::strToJsonValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const in test-479ca2.o
  "Json::Value::operator=(Json::Value)", referenced from:
      BaseHttpHandler::strToJsonValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const in test-479ca2.o
  "HueFinder::GetBridge(HueFinder::HueIdentification const&)", referenced from:
      _main in test-479ca2.o
  "HueFinder::HueFinder(std::__1::shared_ptr<IHttpHandler const>)", referenced from:
      _main in test-479ca2.o
  "Json::CharReaderBuilder::newCharReader() const", referenced from:
      BaseHttpHandler::strToJsonValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const in test-479ca2.o
  "Json::Value::toStyledString() const", referenced from:
      BaseHttpHandler::GETJson(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Json::Value const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) const in test-479ca2.o
      BaseHttpHandler::POSTJson(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Json::Value const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) const in test-479ca2.o
      BaseHttpHandler::PUTJson(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Json::Value const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) const in test-479ca2.o
      BaseHttpHandler::DELETEJson(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Json::Value const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) const in test-479ca2.o
  "vtable for LinHttpHandler", referenced from:
      LinHttpHandler::LinHttpHandler() in test-479ca2.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for HueLight", referenced from:
      HueLight::~HueLight() in test-479ca2.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is it possible it's because I installed jsoncpp with Homebrew ?

**Comment by enwi** [comment]
Are you using clang or gcc? Also are you using cmake for generating the make commands or something else?

**Comment by Apicpic** [comment]
I try with Qt Creator IDE, and now it's work, I succed to find me Hue. Thank you for your help

**Comment by enwi** [comment]
Since this works for you now, I closed this issue. If you have other problems regarding using the library on MacOS just reply to this issue or create a new one, whatever suits you best. Also can you confirm the library working on MacOS by turning lights on/off or using other functions?

**Comment by Apicpic** [comment]
I arrived to connect one time my computer and the Hue but now I have this kind of error : 
LinHttpHandler: Failed to read response from socket: Connection reset by peer
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: LinHttpHandler: Failed to read response from socket: Connection reset by peer
Do you know why ?

**Comment by enwi** [comment]
I will have to check that once I am home, so I can confirm this issue and work out a solution.

**Comment by Apicpic** [comment]
Is it a problem if I have only Local network. I mean if the third led blink ?

**Comment by enwi** [comment]
As long as you are connected to the same network as the Hue bridge and set the correct mac and ip of the bridge you should be able to communicate with it.

**Comment by Apicpic** [comment]
The program is : 
#include <hueplusplus/include/Hue.h>
#include <hueplusplus/include/LinHttpHandler.h>

int main(int argc, char *argv[])
{
    std::cout << "Start the program" << std::endl;
    auto handler = std::make_shared<LinHttpHandler>();
    HueFinder finder(handler);
    std::vector<HueFinder::HueIdentification> bridges;
    if (bridges.empty())
    {
        std::cout << "No found" << std::endl;
        bridges.push_back({"169.254.7.112", "00:17:88:67:A2:4F"});
    }
    std::cout << "End searching for a bridge" << std::endl;

    Hue bridge = finder.GetBridge(bridges[0]);
    std::cout << "Connection ok" << std::endl;

    HueLight light1 = bridge.getLight(1);
    std::cout << "Get light 1" << std::endl;
    std::vector<std::reference_wrapper<HueLight>> lights = bridge.getAllLights();

    light1.On();
    light1.setBrightness(120);
    light1.alertHueSaturation(25500, 255);
    light1.setColorLoop(true);
    light1.setColorRGB(255, 128, 0);
    light1.Off();
    std::cout << "End of the program" << std::endl;
}

And we spam the Philips button I obtain : 
Start the program
No bridge found
End searching for a bridge
Please press the link Button! You've got 35 secs!
Success! Link button was pressed!
Username is "v20R7Xhm9bZbjK8dc1izoJy5CnuGW4F2gsFJsBPr"
Connection ok
LinHttpHandler: Failed to read response from socket: Connection reset by peer
Get light 1
LinHttpHandler: Failed to read response from socket: Connection reset by peer
LinHttpHandler: Failed to read response from socket: Connection reset by peer
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: LinHttpHandler: Failed to read response from socket: Connection reset by peer

And the light become green

**Comment by enwi** [comment]
So I've tested your program and my own on a MacBook Pro running macOS High Sierra v. 10.13.6 and I have no issues whatsoever. What are your system specifications?
Here is my program:
```
#include <LinHttpHandler.h>
#include <Hue.h>

#include <iostream>
#include <unistd.h>

int main()
{
    std::shared_ptr<IHttpHandler> handler(new LinHttpHandler);
    HueFinder hueFinder(handler);
    std::vector<HueFinder::HueIdentification> bridges = hueFinder.FindBridges();
    if (bridges.empty())
    {
        std::cout << "No bridges found!\n";
        bridges.push_back({ "<ip address>", "<mac address>" });
    }
    hueFinder.AddUsername(bridges[0].mac, "<username>");
    Hue test = hueFinder.GetBridge(bridges[0]);

    HueLight light = test.getLight(1);
    light.On();
    usleep(2000000);
    light.Off();
    return 0;
}
```

**Comment by Apicpic** [comment]
I have a macbook Pro 2015 : macOS High Sierra v. 10.13.6. And I connect directly my Bridge to my Mac with the ethernet.

**Comment by enwi** [comment]
It seems to me, that your bridge is not connected to the same network as the PC that you are using. Can you open the internal webpage served by the bridge by openening a browser and typing in the IP-address in the address field?

**Comment by enwi** [comment]
> I have a macbook Pro 2015 : macOS High Sierra v. 10.13.6. And I connect directly my Bridge to my Mac with the ethernet.

So is there a router connected between the bridge and the Mac?

**Comment by enwi** [comment]
Also you need to specify the MAC address without the ':'. So instead of "00:17:88:67:A2:4F" use "00:
178867A24F", that might fix the problem

**Comment by Apicpic** [comment]
I can access to the internal webpage of the bridge in my browser. I try with a rooter and it's the same problem : 
`
LinHttpHandler: Failed to read response from socket: Connection reset by peer
LinHttpHandler: Failed to read response from socket: Connection reset by peer
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: LinHttpHandler: Failed to read response from socket: Connection reset by peer`

**Comment by Apicpic** [comment]
Here there are my complet test projet in Qt Creator IDE, if you can see may be what is wrong. [test.zip](https://github.com/enwi/hueplusplus/files/2349105/test.zip)

**Comment by enwi** [comment]
Your test program is still working for me. But I am using the CMakeLists.txt file (see below) for generating the Makefile and compiling with that. Also did you accept the dialog that pops up when starting the program to accept connections? Other than that I am out of ideas why it might not work.
```
cmake_minimum_required(VERSION 2.8.3)
project(test)

# if we are on a apple machine this is needed
if (1 AND APPLE)
	set(CMAKE_MACOSX_RPATH 1)
endif()

find_package(hueplusplus)
if(NOT hueplusplus_FOUND)
    message(STATUS "-- hueplusplus not found, building it")
    add_subdirectory("${CMAKE_SOURCE_DIR}/../" "${CMAKE_BINARY_DIR}/hueplusplus")
endif()

set(test_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/main.cpp
)

add_executable(test ${test_SOURCES})
set_property(TARGET test PROPERTY CXX_STANDARD 14)
set_property(TARGET test PROPERTY CXX_EXTENSIONS OFF)
set(CMAKE_CXX_FLAGS "-O2") ## Optimize

target_link_libraries(test
                      pthread
                      hueplusplusstatic
)
```

**Comment by enwi** [comment]
I don't know if that makes any difference, but can you try using "00178867a24f" as the mac address?

**Comment by enwi** [comment]
So did you get it working?
