### ISSUE TITLE
Code will compile but not work on GCC =< 4.9.0 

### ISSUE THREAD

**Issue by EmilyBjoerk** [enwi/hueplusplus#22]
https://github.com/enwi/hueplusplus/blob/6d20b6506a350a69f0bc2f6b276c39bc6fac2f14/hueplusplus/Hue.cpp#L44

See:
https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions

Something like: https://stackoverflow.com/a/18369825/2498188 in the cmake file would prevent silent breakage with users.

**Comment by enwi** [comment]
@EmilyBjoerk Thanks for the issue, we will remove the usage of regex and replace it with simple string searches to support probably all c++ versions

**Comment by enwi** [comment]
@EmilyBjoerk Please use the current development version, which includes all changes
