### ISSUE TITLE
Beginner guide

### ISSUE THREAD

**Issue by adelwyr** [enwi/hueplusplus#27]
Hello,

Am a complete beginner.

Is it possible to upload a complete example for linux? 

Am struggling with the finding the bridge (there is not 'LinHttpHandeler') what do i replace it with to run the code to find the Hue bridge?

**Comment by Jojo-1000** [comment]
What do you want to see in the example? Just connecting or also more, like using the lamps?

**Comment by adelwyr** [comment]
Just getting the bridge ip address, am not able to get it with this code: Even thought it's connected and i can access it through postman.

Code `
#include <hueplusplus/Hue.h>

#include <algorithm>
#include <cctype>
#include <chrono>
#include <cstring>
#include <iostream>
#include <locale>
#include <stdexcept>
#include <thread>

#include <hueplusplus/ExtendedColorHueStrategy.h>
#include <hueplusplus/ExtendedColorTemperatureStrategy.h>
#include <hueplusplus/SimpleBrightnessStrategy.h>
#include <hueplusplus/SimpleColorHueStrategy.h>
#include <hueplusplus/SimpleColorTemperatureStrategy.h>

#include <hueplusplus/UPnP.h>

#include <curlpp/cURLpp.hpp>
#include <curlpp/Options.hpp>
#include <curlpp/Easy.hpp>

#include <hueplusplus/LinHttpHandler.h>
#include "hueplusplus/hueplusplus/LinHttpHandler.cpp"
#include "hueplusplus/hueplusplus/jsoncpp.cpp"
#include "hueplusplus/hueplusplus/Hue.cpp"
#include "hueplusplus/hueplusplus/ExtendedColorHueStrategy.cpp"
#include "hueplusplus/hueplusplus/ExtendedColorTemperatureStrategy.cpp"
#include "hueplusplus/hueplusplus/HueCommandAPI.cpp"
#include "hueplusplus/hueplusplus/HueLight.cpp"
#include "hueplusplus/hueplusplus/SimpleBrightnessStrategy.cpp"
#include "hueplusplus/hueplusplus/SimpleColorHueStrategy.cpp"
#include "hueplusplus/hueplusplus/SimpleColorTemperatureStrategy.cpp"
#include "hueplusplus/hueplusplus/UPnP.cpp"
//#include "hueplusplus/hueplusplus/WinHttpHandler.cpp"
#include <string>
#include <typeinfo>

using namespace std;






int main(){

std::shared_ptr<const IHttpHandler> handler;



handler = std::make_shared<LinHttpHandler>();
HueFinder finder(handler);
std::vector<HueFinder::HueIdentification> bridges = finder.FindBridges();
if(bridges.empty())
{
	bridges.push_back({"<ip NO>","<mac address>"});
}

printf("my ip: %s\n",bridges[0].ip.c_str());
printf("hi\n");

std::cout.flush();

return 0;

}
`

Dont mind the extra #includes since wasnt sure about the dependencies. 
I havent been able to get the ip address with this code. What am I doing wrong?

**Comment by Jojo-1000** [comment]
You can post multiline code in triple ` (I edited your comment).
I pushed an example to the branch examples, can you check it out to see if it works?
You need to enable the option "hueplusplue_SAMPLES" in CMakeCache.txt
