### ISSUE TITLE
PIR

### ISSUE THREAD

**Issue by flypie** [enwi/hueplusplus#30]
Is it possible to use the PIR devices in the HUW range via the library?

https://www2.meethue.com/en-gb/p/hue-outdoor-sensor/8718699625474?origin=SRVYRUVW&pcrid=353221187940|mckv|sSRVYRUVW_dc|plid||slid||&gclid=Cj0KCQiAv8PyBRDMARIsAFo4wK29n3qY6xhkTgc0pV7r2dUnYEaVCTMckRCTK_Sj2bf5YSRCJk42sesaAoIGEALw_wcB

**Comment by enwi** [comment]
Not yet
