### ISSUE TITLE
Users of the library cannot detect and act on auth failures

### ISSUE THREAD

**Issue by EmilyBjoerk** [enwi/hueplusplus#32]
While testing my code with deliberately bad username (API key) I ran into the following:

```
Answer in Hue::refreshState of http_handler->GETJson(...) is not expected!
Answer:
	[
   {
      "error" : {
         "address" : "/",
         "description" : "unauthorized user",
         "type" : 1
      }
   }
]
```

Which comes from here:
https://github.com/enwi/hueplusplus/blob/9a3b8d6ca1390c642d051f4b3ac5a72d0379e0d1/hueplusplus/Hue.cpp#L408-L410

The above means that as a user of the library, it's not possible for me to detect the invalid API key and stop my application or handle it by reverting to requesting the user to push the button.

**Comment by enwi** [comment]
@EmilyBjoerk  I've tested your code with the changes made on the development branch and it all works fine.
