### ISSUE TITLE
Switch license from GNU GPLv3 to GNU LGPLv3

### ISSUE THREAD

**Issue by enwi** [enwi/hueplusplus#33]
As the current license is very strong and does not allow to use the HuePlusPlus library when linking it in another project without dislcosing their source, I am opening this issue to ask all contributors if they approve to change the license of the library.

By that I mean @sieren, @Wulkop, @Jojo-1000 and @EmilyBjoerk.
Please write a comment stating whether you are okay with the license change and give me the right to do so.

I hope that this change will make this library more useful to a wider range of people.

**Comment by Jojo-1000** [comment]
I am okay with the license change

**Comment by sieren** [comment]
So am I.

**Comment by Wulkop** [comment]
I am okay with the change.

**Comment by EmilyBjoerk** [comment]
No objections (not sure why I'm on the list tho :shrug:)

**Comment by enwi** [comment]
Thank you all for accepting the license change.

@EmilyBjoerk I needed to ask you too, because I added changes you made to the code.
