### ISSUE TITLE
Hue.cpp does not compile on Raspberry Pi (Debian Linux I think)

### ISSUE THREAD

**Issue by RichardCroxall** [enwi/hueplusplus#50]
Just to emphasise this package is really good. It has saved me a huge amount of time. So I thought that I would contribute back to the project with the following.

In Hue.cpp the following line (line 186 in requestUsername does not compile on Raspberry Pi (linux):
not working:
username = jsonUser;
working:
username = jsonUser.get<std::string>();

Whilst the bonnet is open, also at line 173 the declaration
    nlohmann::json answer;
can be moved to be with the assignment at line 180 for a slightly tidier result. (Picked out by Visual Studio/C# resharper)
nlohmann::json answer = http_handler->POSTJson("/api", request, ip, port);

**Comment by Jojo-1000** [comment]
The json library apparently has some issues with implicit conversions to string with certain compilers or versions. I think the best workaround is to simply remove all implicit conversions from json and always specify the type with `get<T>()`. That makes it harder to read, but in the future, any changes can break these conversions again.
