### ISSUE TITLE
Visual Studio generates warnings on 'C' style enum definitions. Maybe new C++ enum class definitions would be better in the long term.

### ISSUE THREAD

**Issue by RichardCroxall** [enwi/hueplusplus#52]
In C, code all of the values in an enum have global scope. E.g. 
enum ColorType
{
    UNDEFINED, //!< ColorType for this light is unknown or undefined
    NONE, //!< light has no specific ColorType
    GAMUT_A,
    GAMUT_B,
    GAMUT_C,
    TEMPERATURE,
    GAMUT_A_TEMPERATURE,
    GAMUT_B_TEMPERATURE,
    GAMUT_C_TEMPERATURE
};

i.e. UNDEFINED has global scope anywhere huelight.h is included.
If you change the first line of the declaration to:
enum class ColorType
the warning dissappears, but then you have to write ColorType.UNDEFINED to reference the value.

This certainly isn't essential, but could be done at the same time as some more essential changes. Also it is a breaking change in the sense that some user code might stop working, so could make you unpopular.

**Comment by Jojo-1000** [comment]
This is already done on the development branch, along with a whole bunch of other breaking changes. That is one of the reasons why the development branch is not merged into master yet. The idea is to have a full "Version 1.0" done, so we can ideally continue without breaking changes after that.
