### ISSUE TITLE
Add support for 440400982841 and LCA001

### ISSUE THREAD

**Issue by brandonsandoval** [enwi/hueplusplus#62]
I have two types of lights, but unfortunately they don't work with this library, it would be great to add support for more lights:
```
Could not determine HueLight type:440400982841!
Could not determine HueLight type:LCA001!
```
Could we please add support for these lights? Would I just add the lights to Hue.cpp? I can test this out later.

More info on the lights:
https://zigbee.blakadder.com/Philips_LCT024.html
https://zigbee.blakadder.com/Philips_LCA001.html

**Comment by enwi** [comment]
@brandonsandoval Could you try out the development branch, since we changed the way how lights are handled there?
