### ISSUE TITLE
Bridge reconnect

### ISSUE THREAD

**Issue by nandra** [enwi/hueplusplus#63]
Hello, is there in library some functionality which reconnect to Bridge is it was disconnected during operation? Thanks.

**Comment by enwi** [comment]
Each command sent to the bridge opens up its own connection so there is no need to reconnect. If you mean the token, that needs to be retrieved while pressing the button of the bridge, you need to store it and provide to hueplusplus if you restart your program.

**Comment by nandra** [comment]
I mean if e.g. bridge is disconnected from power or lost network how it is handled.

**Comment by enwi** [comment]
There is nothing specific for that case, but you will probably get some Exceptions like
https://github.com/enwi/hueplusplus/blob/83d4883211e61a66867f5736a96c667652ce333e/hueplusplus/LinHttpHandler.cpp#L72
https://github.com/enwi/hueplusplus/blob/83d4883211e61a66867f5736a96c667652ce333e/hueplusplus/LinHttpHandler.cpp#L87
https://github.com/enwi/hueplusplus/blob/83d4883211e61a66867f5736a96c667652ce333e/hueplusplus/LinHttpHandler.cpp#L100
https://github.com/enwi/hueplusplus/blob/83d4883211e61a66867f5736a96c667652ce333e/hueplusplus/LinHttpHandler.cpp#L123
