### ISSUE TITLE
Socket being recreated on every network request for every light

### ISSUE THREAD

**Issue by EmilyBjoerk** [enwi/hueplusplus#64]
I was debugging an issue where my software using hueplusplus stopped working after around a day without fail, running strace on the binary I saw that hueplusplus is repeatedly creating and connecting a socket for each message sent.

After some digging, I found:

https://github.com/enwi/hueplusplus/blob/83d4883211e61a66867f5736a96c667652ce333e/hueplusplus/LinHttpHandler.cpp#L54

Is it an intentional design decision to create a socket connection for each message? This seems inefficient to me, there's overhead associated with opening a socket and TCP benefits from keeping the socket open due to slow start behaviour of congestion control. Would it break anything if the socket was reused between requests?

Edit, also I wouldn't be surprised if the bridge was none too happy about being hammered with new TCP connections due to this...

**Comment by enwi** [comment]
@EmilyBjoerk Looking at the official philips hue forum I found a [thread](https://developers.meethue.com/forum/t/keep-alive/5019/4) about `keep-alive` and there the development team states `The bridge doesn't support "Connection: keep-alive".`. 

So even though I would also advocate reusing the connection it is just not supported yet and if it will in future it will probably only work with newer models of the base station. 

Maybe it is still possible to reuse the socket object somehow, which would at least get rid of some overhead.
