### ISSUE TITLE
Consider returning 0 from SimpleBrightnessStrategy::getBrightness, when the light is turned off

### ISSUE THREAD

**Issue by enwi** [enwi/hueplusplus#7]
When a light is turned off the function does not represent the correct state

**Comment by aggsol** [comment]
*bump* I find that usefule. Is it going to be merged?

**Comment by enwi** [comment]
It would be merged if it is a good idea to return 0 whenever the light is turned off, but it might be useful to get the set brightness even if the light is turned off. The better way to check if a light is turned on or off would be to call the `isOn` function.

**Comment by aggsol** [comment]
@enwi yeah you re right. Close this then.
