### ISSUE TITLE
Hue bridge not responding to GET /description.xml

### ISSUE THREAD

**Issue by drfrankencopter** [enwi/hueplusplus#73]
Thank you for this project/library!

I'm trying to get the BridgeSetup.cpp example working on Windows 7/Visual Studio 2019. I have the project building and linking against the static library, but it claims not to see any bridges.

I have confirmed (using Wireshark) that a GET request is issued to the bridge, and there is an ACK in response, but the bridge does not send any Html/Xml in response.

The packet trace looks like this:

1. My local machine issues the GET /description.xml HTTP/1.0 request (wireshark is calling this a continuation in the Info field)
2. My local machine then issues an [FIN/ACK]
3. The hue bridge ACK's the Get request in (1)
4. The hue bridge ACK's the [FIN/ACK] from (2)
5. My local machine ACK's the [FIN/ACK] from (4)

The bridge never appears to make any attempt to send the Xml data....

By comparison, if I use a browser (Chrome) to get http://192.168.0.102/description.xml, it returns an Http/Xml response.

I do notice that the browser is using Http 1.1, whereas the BaseHttpServer is using Http 1.0.

Could this be the issue?

Any help would be greatly appreciated. If this is the wrong place to post this sort of question, please let me know where I should be posting....

Thanks again; looking forward to getting this working!

**Comment by drfrankencopter** [comment]
Update: I have managed to get it to respond...but I had to modify WinHttpHandler.cpp to prevent the call to shutdown the socket...

If I comment out the following code (around line 140):
`    if (shutdown(connect_socket, SD_SEND) == SOCKET_ERROR)
    {
        int err = WSAGetLastError();
        std::cerr << "WinHttpHandler: shutdown failed: " << err << std::endl;
        throw(std::system_error(err, std::system_category(), "WinHttpHandler: shutdown failed"));
    }`

It connects to my bridge....

**Comment by drfrankencopter** [comment]
Further update....if I move the code block that I referenced earlier to below the while loop that reads the response it continues to work.

It seems that the response to terminate the connection is handled by the bridge before it can respond to the GET request.

**Comment by enwi** [comment]
That's an interesting bug and I think Windows is to blame here 😄 

Do you want to create a PR with the bug fix yourself?

**Comment by enwi** [comment]
Also I saw that you are inteding to make a `Reaper CS extension` and wanted to add that you should have a look at the `Entertainment API`, which this library supports 🙂

**Comment by drfrankencopter** [comment]
> That's an interesting bug and I think Windows is to blame here 
> 
> Do you want to create a PR with the bug fix yourself?

It might be a Windows issue, but it could also be something on the bridge side too. I note in  Microsoft's docs (https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-shutdown) they state that for TCP sockets issuing a shutdown for SD-SEND will cause a FIN to be issued after all data has been sent and acknowledged by the receiver.  I suspect this is normal behaviour, even for BSD sockets. Perhaps with BSD sockets there is a bit more latency in when the FIN is requested. I'll have to try building hueplusplus on my mac and investigate there.

WRT the PR, I'm not really comfortable doing that right now, as this is really my first experience with this project/codebase. That said, I'm happy to post the source changes here, and if they look good/reasonable I can try and go through the PR process.

**Comment by drfrankencopter** [comment]
> Also I saw that you are inteding to make a `Reaper CS extension` and wanted to add that you should have a look at the `Entertainment API`, which this library supports

Good catch; I am indeed intending on coupling hueplusplus to Reaper's CS SDK. 

Thanks for mentioning the Entertainment API. That's awesome...I'm definitely checking it out!

**Comment by Jojo-1000** [comment]
Thank you very much for tracking down this bug.
It came up before, but we were not able to find the root cause.

Can you please take a look at pull request #74 and verify that these changes work for you?
Also let me know if you have any other changes in your version.

**Comment by enwi** [comment]
> PS: Just looked at the SDK for Entertainment mode....so much potential there. I am re-thinking several of my previous ideas as this opens up so many more possibilities.

That is also an option, but hueplusplus also supports the entertainment mode
