### ISSUE TITLE
Getting errors messages when I try and run make(linux)

### ISSUE THREAD

**Issue by BOB450** [enwi/hueplusplus#79]
**Describe the bug**:
When I go to make it only gets to  18 percent then spits out errors something about output being truncated.

**To Reproduce**:
System manjaro Linux. 
1) clone repo
2) cd hueplusplus
3) mkdir build
4) cd build
5) cmake .. (Runs fine with no errors)
6) make (getts to 18 percent then gives a bunch of errors I have tried multiple times on fresh clones of repo always the same.)

**Expected behavior**:
I expected the step 6 to finish without errors

**Desktop (please complete the following information):**
 - OS: Linux(manjaro)
 - Version NA(new)

**Additional context**
If it is me that is doing something wrong let me know I am happy to give more info if necessary.
Thankyou -BOB450

**Console log/Error message**:

[  3%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/aria.c.o
[  3%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/aesni.c.o
[  3%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/arc4.c.o
[  3%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/aes.c.o
[  3%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1parse.c.o
[  3%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1write.c.o
[  3%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/base64.c.o
[  7%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/bignum.c.o
[  7%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/blowfish.c.o
[  7%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/camellia.c.o
[  7%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/ccm.c.o
[  7%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/chacha20.c.o
[  7%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/chachapoly.c.o
[ 11%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/cipher.c.o
[ 11%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/cipher_wrap.c.o
[ 11%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/cmac.c.o
[ 11%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/ctr_drbg.c.o
[ 11%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/des.c.o
[ 11%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/dhm.c.o
[ 14%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/ecdh.c.o
[ 14%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/ecdsa.c.o
[ 14%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/ecjpake.c.o
[ 14%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/ecp.c.o
[ 14%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/ecp_curves.c.o
[ 18%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/entropy.c.o
[ 18%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/entropy_poll.c.o
[ 18%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/error.c.o
[ 18%] Building C object lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/gcm.c.o
/home/user1/hueplusplus/lib/mbedtls/library/error.c: In function ‘mbedtls_strerror’:
/home/user1/hueplusplus/lib/mbedtls/library/error.c:921:47: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
  921 |             mbedtls_snprintf( buf, buflen, "%s", high_level_error_description );
      |                                               ^
In file included from /home/user1/hueplusplus/lib/mbedtls/library/error.c:29:
/home/user1/hueplusplus/lib/mbedtls/include/mbedtls/platform.h:76:41: note: ‘snprintf’ output 1 or more bytes (assuming 2) into a destination of size 1
   76 | #define MBEDTLS_PLATFORM_STD_SNPRINTF   snprintf /**< The default \c snprintf function to use.  */
/home/user1/hueplusplus/lib/mbedtls/include/mbedtls/platform.h:243:28: note: in expansion of macro ‘MBEDTLS_PLATFORM_STD_SNPRINTF’
  243 | #define mbedtls_snprintf   MBEDTLS_PLATFORM_STD_SNPRINTF
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user1/hueplusplus/lib/mbedtls/library/error.c:921:13: note: in expansion of macro ‘mbedtls_snprintf’
  921 |             mbedtls_snprintf( buf, buflen, "%s", high_level_error_description );
      |             ^~~~~~~~~~~~~~~~
/home/user1/hueplusplus/lib/mbedtls/library/error.c:919:46: error: ‘UNKNOWN ERROR CODE (’ directive output truncated writing 20 bytes into a region of size 1 [-Werror=format-truncation=]
  919 |             mbedtls_snprintf( buf, buflen, "UNKNOWN ERROR CODE (%04X)", (unsigned int) use_ret );
      |                                             ~^~~~~~~~~~~~~~~~~~~
/home/user1/hueplusplus/lib/mbedtls/library/error.c:919:44: note: directive argument in the range [1, 65408]
  919 |             mbedtls_snprintf( buf, buflen, "UNKNOWN ERROR CODE (%04X)", (unsigned int) use_ret );
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/user1/hueplusplus/lib/mbedtls/library/error.c:29:
/home/user1/hueplusplus/lib/mbedtls/include/mbedtls/platform.h:76:41: note: ‘snprintf’ output 26 bytes into a destination of size 1
   76 | #define MBEDTLS_PLATFORM_STD_SNPRINTF   snprintf /**< The default \c snprintf function to use.  */
/home/user1/hueplusplus/lib/mbedtls/include/mbedtls/platform.h:243:28: note: in expansion of macro ‘MBEDTLS_PLATFORM_STD_SNPRINTF’
  243 | #define mbedtls_snprintf   MBEDTLS_PLATFORM_STD_SNPRINTF
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user1/hueplusplus/lib/mbedtls/library/error.c:919:13: note: in expansion of macro ‘mbedtls_snprintf’
  919 |             mbedtls_snprintf( buf, buflen, "UNKNOWN ERROR CODE (%04X)", (unsigned int) use_ret );
      |             ^~~~~~~~~~~~~~~~
/home/user1/hueplusplus/lib/mbedtls/library/error.c:958:43: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
  958 |         mbedtls_snprintf( buf, buflen, "%s", low_level_error_description );
      |                                           ^
In file included from /home/user1/hueplusplus/lib/mbedtls/library/error.c:29:
/home/user1/hueplusplus/lib/mbedtls/include/mbedtls/platform.h:76:41: note: ‘snprintf’ output 1 or more bytes (assuming 2) into a destination of size 1
   76 | #define MBEDTLS_PLATFORM_STD_SNPRINTF   snprintf /**< The default \c snprintf function to use.  */
/home/user1/hueplusplus/lib/mbedtls/include/mbedtls/platform.h:243:28: note: in expansion of macro ‘MBEDTLS_PLATFORM_STD_SNPRINTF’
  243 | #define mbedtls_snprintf   MBEDTLS_PLATFORM_STD_SNPRINTF
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user1/hueplusplus/lib/mbedtls/library/error.c:958:9: note: in expansion of macro ‘mbedtls_snprintf’
  958 |         mbedtls_snprintf( buf, buflen, "%s", low_level_error_description );
      |         ^~~~~~~~~~~~~~~~
/home/user1/hueplusplus/lib/mbedtls/library/error.c:956:42: error: ‘UNKNOWN ERROR CODE (’ directive output truncated writing 20 bytes into a region of size 1 [-Werror=format-truncation=]
  956 |         mbedtls_snprintf( buf, buflen, "UNKNOWN ERROR CODE (%04X)", (unsigned int) use_ret );
      |                                         ~^~~~~~~~~~~~~~~~~~~
/home/user1/hueplusplus/lib/mbedtls/library/error.c:956:40: note: directive argument in the range [1, 2147418239]
  956 |         mbedtls_snprintf( buf, buflen, "UNKNOWN ERROR CODE (%04X)", (unsigned int) use_ret );
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/user1/hueplusplus/lib/mbedtls/library/error.c:29:
/home/user1/hueplusplus/lib/mbedtls/include/mbedtls/platform.h:76:41: note: ‘snprintf’ output between 26 and 30 bytes into a destination of size 1
   76 | #define MBEDTLS_PLATFORM_STD_SNPRINTF   snprintf /**< The default \c snprintf function to use.  */
/home/user1/hueplusplus/lib/mbedtls/include/mbedtls/platform.h:243:28: note: in expansion of macro ‘MBEDTLS_PLATFORM_STD_SNPRINTF’
  243 | #define mbedtls_snprintf   MBEDTLS_PLATFORM_STD_SNPRINTF
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user1/hueplusplus/lib/mbedtls/library/error.c:956:9: note: in expansion of macro ‘mbedtls_snprintf’
  956 |         mbedtls_snprintf( buf, buflen, "UNKNOWN ERROR CODE (%04X)", (unsigned int) use_ret );
      |         ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/build.make:440: lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/error.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:911: lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by enwi** [comment]
I think this is related to #77. Could you try to use the development branch? We recently #78 updated mbedtls to fix this issue.

**Comment by BOB450** [comment]
Great that fixed the problem just had to use the development branch.
