### ISSUE TITLE
I'm getting a error when running code snippet 

### ISSUE THREAD

**Issue by BOB450** [enwi/hueplusplus#80]
**Describe the bug**:
When attempting to run the code snippet provided in the readme I get an error.

**Expected behavior**:
To not get an error.

**Console log/Error message**:
 error: undefined reference to`hueplusplus::BridgeFinder::BridgeFinder(std::shared_ptr<hueplusplus::IHttpHandler const>)'

**AND**

undefined reference to `hueplusplus::BridgeFinder::findBridges() const'

**AND**

error: undefined reference to `vtable for hueplusplus::BaseHttpHandler'

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version NA

**Additional context**
I was trying to connect to the bridge using the provide code snipet

    auto handler = std::make_shared<hueplusplus::LinHttpHandler>();
    hue::BridgeFinder finder(handler);
    std::vector<hueplusplus::BridgeFinder::BridgeIdentification> bridges = finder.findBridges();
    if (bridges.empty())
    {
        //std::cerr << "No bridges found\n";

    }

Thankyou BOB450

**Comment by BOB450** [comment]
and I am including all necessary header files I think.
#include <hueplusplus/Bridge.h>
#include <hueplusplus/LinHttpHandler.h>
#include <hueplusplus/BaseDevice.h>
#include <hueplusplus/IHttpHandler.h>
#include <hueplusplus/BaseHttpHandler.h>
#include <hueplusplus/LinHttpHandler.h>

**Comment by enwi** [comment]
Have you tried one of the [examples](https://github.com/enwi/hueplusplus/tree/development/examples) yet?

**Comment by BOB450** [comment]
Ya, I Tried to run The bridge Setup example and got some errors I compiled with g++ bridgeSetup.cpp. Do I need to use g++ flag that I'm not?

ERRORS
/usr/bin/ld: /tmp/ccoIRVVo.o: warning: relocation against `_ZTVN11hueplusplus15BaseHttpHandlerE' in read-only section `.text._ZN11hueplusplus15BaseHttpHandlerC2Ev[_ZN11hueplusplus15BaseHttpHandlerC5Ev]'
/usr/bin/ld: /tmp/ccoIRVVo.o: in function `connectToBridge()':
BridgeSetup.cpp:(.text+0x61): undefined reference to `hueplusplus::BridgeFinder::BridgeFinder(std::shared_ptr<hueplusplus::IHttpHandler const>)'
/usr/bin/ld: BridgeSetup.cpp:(.text+0x98): undefined reference to `hueplusplus::BridgeFinder::findBridges() const'
/usr/bin/ld: BridgeSetup.cpp:(.text+0x246): undefined reference to `hueplusplus::BridgeFinder::getBridge(hueplusplus::BridgeFinder::BridgeIdentification const&, bool)'
/usr/bin/ld: BridgeSetup.cpp:(.text+0x281): undefined reference to `hueplusplus::BridgeFinder::addUsername(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: BridgeSetup.cpp:(.text+0x368): undefined reference to `hueplusplus::BridgeFinder::getBridge(hueplusplus::BridgeFinder::BridgeIdentification const&, bool)'
/usr/bin/ld: /tmp/ccoIRVVo.o: in function `main':
BridgeSetup.cpp:(.text+0x49c): undefined reference to `hueplusplus::Bridge::getBridgeIP[abi:cxx11]() const'
/usr/bin/ld: BridgeSetup.cpp:(.text+0x4df): undefined reference to `hueplusplus::Bridge::getUsername[abi:cxx11]() const'
/usr/bin/ld: /tmp/ccoIRVVo.o: in function `hueplusplus::BaseHttpHandler::BaseHttpHandler()':
BridgeSetup.cpp:(.text._ZN11hueplusplus15BaseHttpHandlerC2Ev[_ZN11hueplusplus15BaseHttpHandlerC5Ev]+0x1b): undefined reference to `vtable for hueplusplus::BaseHttpHandler'
/usr/bin/ld: /tmp/ccoIRVVo.o: in function `hueplusplus::LinHttpHandler::LinHttpHandler()':
BridgeSetup.cpp:(.text._ZN11hueplusplus14LinHttpHandlerC2Ev[_ZN11hueplusplus14LinHttpHandlerC5Ev]+0x1b): undefined reference to `vtable for hueplusplus::LinHttpHandler'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status

Pretty much the same errors I was getting when I was trying to compile my own program using the library.

**Comment by enwi** [comment]
Have you looked at the documentation on how to build?
https://enwi.github.io/hueplusplus/build.html

**Comment by BOB450** [comment]
I tried to follow the instructions for the example 
I'm using cmake version 3.21.3

mkdir build
cd build
cmake .. -Dhueplusplus_TESTS=ON (GOT A ERROR ON THIS COMMAND)

-- Submodule update
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Configuring done
-- Generating done
-- Build files have been written to: /home/user1/hueplusplus/build/test/googletest-download
[ 11%] Performing download step (git clone) for 'googletest'
Cloning into 'googletest-src'...
fatal: invalid reference: master
CMake Error at googletest-download/googletest-prefix/tmp/googletest-gitclone.cmake:40 (message):
  Failed to checkout tag: 'master'


make[2]: *** [CMakeFiles/googletest.dir/build.make:99: googletest-prefix/src/googletest-stamp/googletest-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/googletest.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
CMake Error at test/CMakeLists.txt:15 (message):
  Build step for googletest failed: 2

**Comment by enwi** [comment]
Please switch to [gtest-update](https://github.com/enwi/hueplusplus/tree/gtest-update) branch or replace `-Dhueplusplus_TESTS=ON` with `-Dhueplusplus_EXAMPLES=ON`. You might need to add `-Dhueplusplus_TESTS=OFF`, since you turned it on. The gtest error is another error you stumbled across where google renamed the main branch.

**Comment by BOB450** [comment]
Thank you I switched to the new branch and reinstalled and built the examples without a hitch and was able to run the examples without an error.

**Comment by enwi** [comment]
Once the branch is merged #81 you can switch back to the development branch, if ever needed 🙂

**Comment by BOB450** [comment]
ok, will do ill stick to the gtest branch for now.
