### ISSUE TITLE
Entertainment Group creation fails with API error

### ISSUE THREAD

**Issue by danielskeenan** [enwi/hueplusplus#84]
**Describe the bug**:
When creating a new Entertainment Group, the bridge responds with error 5 ("missing parameters in body").

**To Reproduce**:
1. Instantiate and authenticate with a bridge.
2. Attempt to create a new entertainment group like:
```cpp
bridge.groups().create(hueplusplus::CreateGroup::Entertainment({"1"}, "my group"));
```
3. Observe the `HueAPIResponseException` (details below).

**Expected behavior**:
The group is created.

**Console log/Error message**:
The exceptions `what()` returns:
```
HueApiResponseException from create in /usr/local/include/hueplusplus/ResourceList.h:304 5 /groups/class invalid/missing parameters in body
```

**Desktop (please complete the following information):**
 - OS: Kubuntu 21.10

**Additional context**
 - Bridge software: 1.49.1949203030

**Comment by Jojo-1000** [comment]
The hue documentation is not very clear on this, but it may be only possible to create the entertainment setups from within the app.

**Comment by danielskeenan** [comment]
Yeah the docs are pretty bad... Specificlly it seems this line from the [Groups API page](https://developers.meethue.com/develop/hue-api/groupds-api/#create-group) has changed in the implementation without updating docs (maybe tied to API v2?):

> Note: For room creation the room class has to be passed, without class it will get the default: “Other” class.

As a test, I changed CreateGroup::getRequest() to always set the class, defaulting to "Other" if none was passed.  Can't tell if there are other consequences for this, but happy to create a PR.

**Comment by Jojo-1000** [comment]
Feel free to create a pull request with your changes. Maybe we should also remove the entertainment option for CreateGroup, if it doesn't work.
