### ISSUE TITLE
json.exception.parse_error.101 when getting access to lights

### ISSUE THREAD

**Issue by DoubVarial** [enwi/hueplusplus#87]
**Describe the bug**:
I created a Bridge object with the IP, Port and username of my bridge. Now I want to get access to the lights of my Hue-system, where a json parse error is thrown. 

**To Reproduce**:
I used some of the code-snippets of the getting-started section and the BridgeSetup.cpp example:

```
#include <algorithm>
#include <iostream>

#include <hueplusplus/Bridge.h>

#ifdef _MSC_VER
#include <hueplusplus/WinHttpHandler.h>

using SystemHttpHandler = hueplusplus::WinHttpHandler;

#else
#include <hueplusplus/LinHttpHandler.h>

using SystemHttpHandler = hueplusplus::LinHttpHandler;

#endif

namespace hue = hueplusplus;

// Connects to a bridge and returns it.
hue::Bridge connectToBridge()
{
    auto handler = std::make_shared<hueplusplus::WinHttpHandler>();
    hueplusplus::Bridge bridge("MyIP", 80, "<MyUsername>", handler);

    return bridge;
}
int main(int argc, char** argv)
{
    try
    {
        hue::Bridge hue = connectToBridge();
        std::cout << "Connected to bridge. IP: " << hue.getBridgeIP() << ", username: " << hue.getUsername() << '\n';
        std::vector<hueplusplus::Light> lights = hue.lights().getAll();   
    }
    catch (nlohmann::json::parse_error& e)
    {
        std::cout << e.what() << '\n';

    }

    std::cout << "Press enter to exit\n";
    std::cin.get();

    return 0;
}
```
**Expected behavior**:
I want to get the vector of the lights in my Hue-system

**Console log/Error message**:
`[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<'`

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Visual Studio 2022

**Comment by enwi** [comment]
@DoubVarial You cannot use `<MyUsername>` as the username, please choose sth. else

**Comment by DoubVarial** [comment]
Thanks for your answer!
I did not use `<MyUsername>`, but the correct username of my Hue-System. It seems that my Bridge cannot be found. I added the code-snippet with Hue-Finder and get the message `No bridges found`:
```

#include <algorithm>
#include <iostream>

#include <hueplusplus/Bridge.h>

#ifdef _MSC_VER
#include <hueplusplus/WinHttpHandler.h>

using SystemHttpHandler = hueplusplus::WinHttpHandler;

#else
#include <hueplusplus/LinHttpHandler.h>

using SystemHttpHandler = hueplusplus::LinHttpHandler;

#endif

namespace hue = hueplusplus;

int main(int argc, char** argv)
{
    
    try
    {
        
        auto handler = std::make_shared<hueplusplus::WinHttpHandler>();
        hueplusplus::BridgeFinder finder(handler);
        std::vector<hueplusplus::BridgeFinder::BridgeIdentification> bridges = finder.findBridges();
        if (bridges.empty())
        {
            std::cerr << "No bridges found\n";
            
        }
    }
    catch(...)
    {
        std::cout << "Error" << '\n';
    }

    std::cout << "Press enter to exit\n";
    std::cin.get();

    return 0;
}
```

My bridge's modelid is `BSB002` and uses apiversion `1.56.0`
Do you have more tips for troubleshooting?
Thank your very much!

**Comment by enwi** [comment]
My bridge has software version 1.56.1956178040 and is found using the [example](https://github.com/enwi/hueplusplus/blob/master/examples/BridgeSetup.cpp)

**Comment by enwi** [comment]
@DoubVarial Is `BSB002` an older or newer model? I guess older since you have a lower software version?

**Comment by enwi** [comment]
Can you try updating the software on your bridge?
